---
openapi: 3.0.3
info:
  title: API V1
  version: ver_1
paths:
  "/users":
    post:
      summary: Registers user
      tags:
      - Users
      parameters:
      - name: email
        in: user
        required: true
        schema:
          type: string
      - name: password
        in: user
        required: true
        schema:
          type: string
      - name: password_confirmation
        in: user
        required: true
        schema:
          type: string
      - name: name
        in: user
        required: true
        schema:
          type: string
      - name: description
        in: user
        required: false
        schema:
          type: string
      - name: birthdate
        in: user
        required: false
        format: date
        schema:
          type: string
      - name: website
        in: user
        required: false
        schema:
          type: string
      - name: location
        in: user
        required: false
        schema:
          type: string
      responses:
        '201':
          description: user created
          content: {}
        '422':
          description: Invalid data
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    description:
                      type: string
                    birthdate:
                      type: string
                      format: date
                    website:
                      type: string
                    location:
                      type: string
                    name:
                      type: string
    patch:
      summary: Edit user
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: current_password
        in: user
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Updated
          content: {}
        '401':
          description: Not authorized
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    current_password:
                      type: string
                    password:
                      type: string
                    description:
                      type: string
                    website:
                      type: string
                    location:
                      type: string
    put:
      summary: Edit user
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: current_password
        in: user
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Updated
          content: {}
        '401':
          description: Not authorized
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    current_password:
                      type: string
                    password:
                      type: string
                    description:
                      type: string
                    website:
                      type: string
                    location:
                      type: string
  "/users/sign_in":
    post:
      summary: Login user
      tags:
      - Users
      parameters:
      - name: email
        in: user
        required: true
        schema:
          type: string
      - name: password
        in: user
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Logged in
          content: {}
        '401':
          description: Invalid credentials
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
                required:
                - user
  "/users/sign_out":
    delete:
      summary: Sign out user
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Signed out
          content: {}
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.example.com
