---
openapi: 3.0.1
info:
  title: API V1
  version: ver_1
paths:
  "/users":
    post:
      summary: Registers user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '422':
          description: Invalid data
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    description:
                      type: string
                    birthdate:
                      type: string
                      format: date
                    website:
                      type: string
                    location:
                      type: string
                    name:
                      type: string
              required:
              - email
              - password
              - password_confirmation
              - name
              - birthdate
  "/users/sign_in":
    post:
      summary: Login user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Logged in
          content: {}
        '401':
          description: Invalid credentials
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              required:
              - email
              - password
  "/users/sign_out":
    delete:
      summary: Log out
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '204':
          description: User logged out
          content: {}
securityDefinitions:
  Bearer:
    description: Bearer JWT Token
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.example.com
